.TH yFONT 5 2010-Aug "linux" "heatherly custom programming manual"

.SH NAME
TXF \- fast, clean, aesthetic pre-rendered texture mapped fonts

.SH DESCRIPTION
TXF is an intermediate font file format used to speed and simplify opengl
programming.  the yFONT library allows opengl programs to rapidly display
text using one or more specific pre-rendered TXF font files.

.SH CREATION
TXF files are created by the yFONT_make utility using the freetype library,
a specific ttf font, some font settings, and a predetermined, limited
character set.  the resulting TXF file contains a fast loading texture with
all requested characters pre-rendered and ready to draw.  each TXF file is
unique and contains a single font rendered at a requested point size.

.SH FILE FORMAT
a txf file has three sections...
   header   with overall font charactersitics
   index    with information on all included letters/glyphs
   map      of all glyphs (binary image data)

.SH HEADER

   type    bytes   contents         description
   ---(file type = 10)------
   char    1       magic id         xFF or \377 or 11111111
   char    4       magic number     txf 
   char    5       version          9.9a  (yFONT library version number)
   ---(font info = 21)------
   char    20      font name        alphanumeric
   char    1       point size       +6 to +99
   ---(stat/data =  9)------
   int16   2       texture width    +1 to +9999
   int16   2       texture height   +1 to +9999
   char    1       max ascent       +0 to +100
   char    1       max descent      -0 to -100
   char    1       margin           +1 to +10
   int16   2       gylph count      +1 to +9999

.SH INDEX

   type    bytes   contents         description
   ---(identifier)----------
   int32   4       unicode          standard character identification
   char    1       good             good (y), bad (-)
   ---(texture)-------------
   int16   2       x-position       x-pos inside texture
   int16   2       y-position       y-pos inside texture
   char    1       width            space taken inside texture
   char    1       height           space taken inside texture
   ---(placement)-----------
   char    1       x-offset         offset for placement in opengl
   char    1       y-offset         offset for placement in opengl
   char    1       advancement      advancement for next character

.SH AUTHOR
rsheatherly

.SH SEE ALSO
 yFONT (0)       overview, reasoning, and descision process
 yFONT (3)       library usage and interface
 yFONT (7)       file format
 yFONT_make (1)  creating a new font file
 yFONT_show (1)  reviewing an existing font file

.SH COLOPHON
this page is part of a documentation package mean to make our use of the
heatherly libraries easier and faster
